global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "ddos_rules.yml"
  - "security_rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets: []

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: 'nginx-exporter'
    static_configs:
      - targets: ['nginx-exporter:9113']

  - job_name: 'fail2ban-exporter'
    static_configs:
      - targets: ['fail2ban-exporter:9191']

  # NPM metrics from logs
  - job_name: 'npm-logs'
    static_configs:
      - targets: ['nginx-proxy-manager:81']
    metrics_path: '/metrics'
    scrape_interval: 10s